/** Declaration file generated by dts-gen */

declare module "circom" {
    export function c_tester(circomFile: any, _options: any): any

    export function compiler(srcFile: any, options: any): void

    export function tester(circomFile: any, _options: any): any

    export function wasm_tester(circomFile: any, _options: any): any
}
